import "@/app/globals.css";
import "@/app/assets/materialize.css";
import "@/app/assets/style.css";
import MainHeader from "@/components/main-header/main-header";
import PageTransitionLoader from "@/components/page-transition-loader";

export const metadata = {
  title: "Jamie Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
  },
};

export default function FrontedLayout({ children }) {
  return (
    <html lang="zh-tw">
      <body>
        <PageTransitionLoader />
        <MainHeader />
        <main className="main-below-fixed-header">{children}</main>
      </body>
    </html>
  );
}
